### ISSUE TITLE
Describe relationship between DPLA MAP and PCDM

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#1]
Responsible: @no-reply @azaroth42
Approver: @anarchivist?
Consulted: @mjgiarlo @guegueng
Informed: @anarchivist 

Complete when there is a public description of how DPLA MAP and PCDM can be used together.

**Comment by no-reply** [comment]
I think the main issue here is to draw the connections between `dpla:SourceResource` and `ore:Aggregation` in DPLA MAP, and `pcdm:Object`.

It's easy enough to say that `dctype:Collection` is a equivalent class or subclass of `pcdm:Collection`. An `edm:WebResource` is generally going to be a `pcdm:File`, or a non-repository resource. But there's a little bit of a disconnect when we come to mapping `pcdm:Object` membership structures into MAP.

**Comment by azaroth42** [comment]
:+1: Whiteboarding seems like a necessary first step for progress

**Comment by no-reply** [comment]
Issue for PCDM: is `hasMember` transitive? What are the implications for collection membership?

**Comment by no-reply** [comment]
Some decisions:
- A `pcdm:Object` that is not `hasMember` of another `pcdm:Object` will be treated as a `dpla:SourceResource`.
- Such objects **MUST** have a stable web URL.
- Such objects **SHOULD** have a preview (e.g. a thumbnail).

**Comment by anarchivist** [comment]
Added @guegueng to `consulted`
