### ISSUE TITLE
Determine modeling team working mode / outputs

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#11]
@azaroth42 and @no-reply to decide the following:
- [x] Communication: Slack / calls / emails / issue comments / mixture ?
- [x] Process: PR to master from branch / other ?
- [ ] Outputs: Markdown [+jekyll?] / Wiki /  GDoc / other ?

List to be extended as needed :)

**Comment by mjgiarlo** [comment]
@azaroth42 @no-reply I suspect this is mostly decided. Yes?

**Comment by azaroth42** [comment]
I think so :)

**Comment by mjgiarlo** [comment]
:shipit:
