### ISSUE TITLE
Access, Control and Modeling

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#16]
@mjgiarlo @no-reply @hannahfrost @cbeer 

Scenario 1a suggests access methods and restriction of access conditions:

> She indicates that the images should be available online in JPEG2000 format with zoom and rotate but that the item cannot be downloaded as a high-resolution copy.

To what extent do we think this is a modeling concern, versus engineering? It needs to be recorded somewhere, and see the Hydra/Fedora WebACL convergence thread for access conditions, but the story is clear that the curator specifies at object creation time the desired user interactions. I anticipate, then, that the curator can choose _not_ to do this, such as to make it available only as metadata but to store the images? Or via some non zooming UI? 

My proposal would be that Access Conditions are WebACL and thus an engineering concern.  And that curator selection of access UI is a customization topic for much later, but that the curator should be able to select model templates that have associated UI patterns [book vs postcard vs single image].

**Comment by mjgiarlo** [comment]
:+1: @azaroth42

**Comment by azaroth42** [comment]
Discussion around APOs makes this a bit fuzzier. It would be good to discuss the overlaps between ACLs and APOs, and especially what is machine actionable versus what needs to be maintained, but for documentation purposes.

Another complication is sub-resource level access restrictions.  The scenarios are clear that deep zoom (via tiles) can be allowed at the same time as not allowing access to the full image at full resolution.  While this is possible in IIIF, the extent to which it needs to be described in the model in the repository, to feed the IIIF system, is unclear.

**Comment by azaroth42** [comment]
In the IR case, allowing resource level access control (rather than object level) is important for cases like an open access thesis or dissertation, restricted access of a derivative dataset, and no access to PII containing interview transcripts that went into the creation of the dataset.   The object is still the thesis submission, however the components have different interaction patterns.

When there are better APIs around audio and video, the same component level distinctions will likely apply -- can get DRMed version, but not full. Can get downsampled version. Can stream in 30 second chunks, but not download. And so forth.

**Comment by jcoyne** [comment]
:+1: to using APOs as the default. The only use case they don't support well is "share this document only with Mike and Rob", I suspect that is not too common. We could ask PSU for usage data on this.
:+1: to using access controls at the object level.

**Comment by no-reply** [comment]
Flagging this for continued discussion next week.

**Comment by azaroth42** [comment]
Proposal from @anarchivist and @azaroth42 to prioritize this issue as low unless there are clear use cases to drive decisions, and engineering efforts available to implement them.

**Comment by azaroth42** [comment]
@hybox/drs-team Is IP based authentication a requirement for engineering to implement as part of HyBox? There is a question about highly dynamic group membership (e.g. the set of people who are accessing a resource from an IP range changes constantly)

**Comment by azaroth42** [comment]
@hybox/drs-team Do we ever authorize actions based on non-repository membership in a group?  For example, organizational groups that should be maintained outside of the repository and not reflected into the repo.

**Comment by no-reply** [comment]
Some related modeling proposals are summarized in https://github.com/hybox/models/issues/6#issuecomment-200571261

**Comment by azaroth42** [comment]
Did we get answers for the above questions? If yes, can they be linked/summarized, and then we can close this issue?

**Comment by mjgiarlo** [comment]
Pinging @hybox/drs-team re: :arrow_heading_up:

**Comment by azaroth42** [comment]
As a proposal (easier to react to something than not):
- Yes IP based auth is going to be a requirement, because it is for many institutions right now.  So ... we need to figure out how that interacts with ACLs and the model.
- No, external groups are never important to the repository directly ... if they are, then they need to be recreated within the scope of the repository, either automatically with some LDAP / Groupwise / whatever connector, or manually.

**Comment by mjgiarlo** [comment]
I'm :100: :ok: with that.
