### ISSUE TITLE
Non Structural Resources need Models

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#18]
"Things":
- [x] Agent (Person, Organization, Software?)
- [x] User Account?
- [x] Place
- [ ] Identifier

Concepts:
- [ ] Topic, Subject, Concept    (Philosophy vs Architecture)
- [ ] Form (Postcard vs Book)
- [ ] Genre (Scifi vs Horror)

Not needed:
- RWO Event model, but yes down the line for repository event model

**Comment by azaroth42** [comment]
Decision for User Account (separate from Person) model could be driven by business? How are accounts and roles managed? [Related to #6 ... perhaps now even duplicate of]

**Comment by jcoyne** [comment]
We've done significant work on alexandria (UCSB), largely based on the Oregon Digital model that supports this as linked data (loc, getty, geonames, local).  It also supports Agents and Topics as local models (in Fedora). If we wanted to do this modeling entirely locally, we could use that existing work.  If we wanted to do _real_ linked data we could, but it makes the infrastructure significantly more complex.

**Comment by no-reply** [comment]
This is more of an engineering/architecture question than a modeling one, but:

Do we expect these resources to be repository objects? I.e. is a `Place` an LDP-RS that will be managed independently of any particular object linking to it? Or do these go in a sidecar triplestore/LD Fragments server/...?

A loose guess would be fine, but it would be helpful to know what options are on the table.

@mjgiarlo @atz @jcoyne (please flag anyone else who should weigh in on this question).

**Comment by jcoyne** [comment]
Yes, I think they ought to be repository objects, in that the data make no sense if they (Agents/Places) are not preserved.

I think these potentially could go into a caching/sidecar triplestore, but they don't have to if they have a canonical place in Fedora.  I'm not sure of how much of a say I get here, but my feeling is that we should not try to link against external sources for the first version.  Scoping it in this way reduces the number of problems we need to tackle now.

**Comment by azaroth42** [comment]
:+1: to @jcoyne. Especially for people, who might also need to be linked to user accounts with roles for the repository.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 

> I'm not sure of how much of a say I get here...

You get as much of a say as any of us. :)

**Comment by jcoyne** [comment]
@azaroth42 did you intentionally close this?

**Comment by azaroth42** [comment]
Nope! That's ... odd ...

**Comment by no-reply** [comment]
See #25, #26, & #27.

**Comment by azaroth42** [comment]
Not sure there's anything to do here that isn't captured in the issues specific to each model. Closing. Reopen, or create a new more specific issue if there's something I've missed :smile_cat:
