### ISSUE TITLE
Modeling scope is limited to end-user tools

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#21]
Proposal is that modeling for things that are not end-user focused is out of scope for the first phase of work. And without good reason, hopefully for all eternity, lest FRBRthulhu-14 devour our brains.

Example would be "needing" to find the average width of all of the books in a certain subject so space planning of shelves can take place from an estimation of width \* (number of new books - number of old books deaccessioned). Sure, you could do that. You might want to generate any of a zillion different reports like that... but that isn't the job of HyBox, as a _digital repository_.

**Comment by mjgiarlo** [comment]
:+1: to the maxxxx

**Comment by anarchivist** [comment]
I'd, uh, change the title of this issue, but yeah. :+1:

**Comment by hannahfrost** [comment]
my :+1: is biggest of all

**Comment by no-reply** [comment]
I think we can mark this as closed.

We have more [FRBRthulhu-14 discussion to have](https://github.com/hybox/models/issues/17#issuecomment-197643805) at LDCX, but I think we're in agreement around the point raised here and can use it as guidance for further issues.
