### ISSUE TITLE
Towards megathread #17, are multiple filesets per part in scope?

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#22]
Dear Business folks ( @anarchivist @ggeisler @hannahfrost @tomcramer @ other people, lacking a Team to tag... )

Are any of the following in scope for HyBox without significant major version bump and likely data remediation from a previous version:
- Derivatives from a master file, with their own derivatives (e.g. raw TIFF, plus cropped and color corrected version, each with separate thumbnails) [@hannahfrost and I thought that this was in scope on Tuesday]
- Multiple media types associated with a single part. (e.g. image and video, or image and text, or video and audio, or ...)
- Multiple digitizations of the same page (e.g. 1970s black and white, 2000s full color or depositor supplied vs done in house) and maintaining the distinguishing features (e.g. date, agent, etc)
- Storage optimization -- it would be nice to allow infrequently used representations to be managed on slower storage compared to the access copy (plus access derivs).
- Partial digitizations or distributed digitizations (In the worst/most interesting real case ... BNF holds the excised illumination, BVMM holds the folio ... but wind back down to in-scope scenarios where one institution holds both parts)

**Comment by azaroth42** [comment]
Created a team and put people in it. Hope that's okay. :) [edited]

**Comment by anarchivist** [comment]
[edit to remove administrivia]

Anyhow... 

> - Derivatives from a master file, with their own derivatives :+1: 
> - Multiple media types associated with a single part. **Use case?**
> - Multiple digitizations of the same page ... and maintaining the distinguishing features (e.g. date, agent, etc) **Feels like a stretch.**
> - Storage optimization **Is this a data modeling consideration?**
> - Partial digitizations or distributed digitizations  **What is the assumption about how these relationships would be tracked?**

**Comment by azaroth42** [comment]
No idea, feel free to fix name of team and people who should be in it :)
- Given this :+1: then the rest are gravy. But to fill them in:
- Text transcription in TEI plus page image in PNG. Image of the page, plus audio performance of the music depicted in the page. Dataset for thesis in Excel with Readme in plain text. Chapter in LaTeX and EPS diagrams. Audio file with image thumbnail. (etc.)
- I've run in to it several times, but okay to be out of scope.
- In the current context I think it is, because the pushback against the model is around technical optimization.  If one is a valid negative, then there's an equally (IMHO) valid counter point from the same domain. If we throw out them both ... then there's also no problem :)
- No assumptions yet ... but if it's a use case, then we need multiple FileSets associated with each Page, regardless of the details for the resulting model.

**Comment by anarchivist** [comment]
cc @hybox/drs-team

**Comment by hannahfrost** [comment]
@azaroth42 With introductory caveats as my head is really hazy today. I don't totally understand the question. Are you asking if these are still in scope for near term modeling, or asking if support for these use cases can be deferred?

**Comment by anarchivist** [comment]
cc @saverkamp (for outside hybox use cases probably worthy of separate discussion)

**Comment by no-reply** [comment]
@hannahfrost this set of questions is motivated by the discussion in #17. Several proposed options there preclude (or at least significantly complicate) these use cases.

If we don't choose a model that supports these, adding them later would mean a major HyBox version and a data migration for existing users. So the practical question is whether that would be an acceptable outcome.

**Comment by hannahfrost** [comment]
@no-reply Thanks. @azaroth42 just clarified as well. For me, the top two bullets are certainly squarely in scope, so that should settle it.

**Comment by azaroth42** [comment]
Alright, let's call it done :smile_cat: I think think we can close this issue, and will propose closing #17.
