### ISSUE TITLE
Strawperson model for Person

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#25]
Select most useful subset of FOAF as a strawperson

**Comment by azaroth42** [comment]
Strawprofile:

Person:
- rdf:type foaf:Person
- foaf:name, foaf:familyName, foaf:givenName, foaf:gender, schema:additionalName, schema:honorificPrefix, schema:honorificSuffix
- foaf:mbox, foaf:homepage
- schema:birthDate, schema:birthPlace, schema:deathDate, schema:deathPlace
- schema:affiliation
- schema:nationality
- foaf:knows

**Comment by azaroth42** [comment]
#6 has the model for how accounts and people fit into the overall model. Removed account from the strawprofile.

**Comment by azaroth42** [comment]
Note that the above is based on the information managed by LCNAF, such as:
  http://id.loc.gov/authorities/names/n79005673.html

Note that LCNAF RDF is not usable directly, as the authority identifies a Concept, not a Person.

**Comment by no-reply** [comment]
Seems like a reasonable set of base properties, assuming they are optional (all of them? do we need a base `label` property for all of these classes?).

:+1: to `foaf:Person`, for sure.

**Comment by no-reply** [comment]
> Note that LCNAF RDF is not usable directly, as the authority identifies a Concept, not a Person.

:+1:

**Comment by azaroth42** [comment]
So ....  rdfs:label vs foaf:name?

**Comment by no-reply** [comment]
@azaroth42 Based on conversation with @hybox/drs-team group membership transitivity needs to be back on the table.

I'm going to ask them to generate user stories for that.

**Comment by no-reply** [comment]
We also have a open question about the need to have context-specific names.

If an author is credited under multiple names on different objects, we may need to be able to model the distinction. 

@hannahfrost we would like to follow up on this.

**Comment by no-reply** [comment]
@hybox/drs-team suggests looking at ULAN for possible descriptive metadata.

**Comment by azaroth42** [comment]
rdfs:label and foaf:name (plus other name-y properties) are both useful. For example, a _label_ of "Anonymous" or "Master of the Berry Apocalypse" is good, whereas those are clearly not _names_.

**Comment by azaroth42** [comment]
Context specific names seems very difficult, as it would mean reifying the name literals. I would push this out of scope unless there is a well established business value associated with it.
