### ISSUE TITLE
Strawperson model for Place

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#26]
Most useful subset of geonames? Pull in @mejackreed.

**Comment by mejackreed** [comment]
Let me know what you mean and happy to contribute.

**Comment by no-reply** [comment]
[DPLA MAPv4](http://dp.la/info/wp-content/uploads/2015/03/MAPv4.pdf) uses `edm:Place`, assuming a base compatibility with `geonames:Feature` (this makes it a subclass of `schema:Place`). This compatibility is improved in Geonames Ontology 3.1, which removes cardinality constraints from `gn:Feature`. 

It may be worth looking at the status of ongoing work of the W3C [Spatial Data on the Web WG](https://www.w3.org/2015/spatial/wiki/Main_Page).

A few questions:
- Do we have use cases for cartographic points, bounding boxes, polygons, multi-polygons, and/or all of the above?
- Do we have use cases for geographic/administrative feature hierarchies?

**Comment by no-reply** [comment]
Feature hierarchies are welcome in the same way as broader/narrower concepts.

**Comment by azaroth42** [comment]
What relationships are there from resources to Places? dcterms:spatial (which seems like it could just be subject, no?) schema:birthPlace / deathPlace ... we should have some sort of place of creation (bf:originPlace ?).  There isn't an event model, which would be the obvious place for it.

**Comment by anarchivist** [comment]
We should add `dcterms:spatial` for the sake of alignment with DPLA MAPv4. 

Closing, because documentation exists.
