### ISSUE TITLE
Strawperson model for Concepts

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#27]
Most useful subset of SKOS for topic, genre, form.

**Comment by no-reply** [comment]
@hybox/drs-team:
- Are there external controlled vocabularies/concept schemes we intend to support?
- Is there a requirement to be able to introduce additional or custom controlled vocabularies?
- Do we have use cases for KOS features, e.g. broader/narrower concepts; related concepts... ?

**Comment by hannahfrost** [comment]
@no-reply Yes to point 1 and 2 above. Not sure about point 3. @guegueng and I will work further on a response.

**Comment by azaroth42** [comment]
I think that (2) is the important one for us at this stage -- meaning that there must be some way to manage controlled vocabularies. At that point a full on KOS is icing, but the core that could be expanded to it is required regardless.

**Comment by no-reply** [comment]
![image](https://cloud.githubusercontent.com/assets/1361776/14004554/32c80532-f118-11e5-92c6-4621091db23b.png)

Need to follow up on the requirements questions from above, but otherwise we think this is ready to ship.

**Comment by no-reply** [comment]
The soft inclusion of broader/narrower etc... sounds good, per @hybox/drs-team discussion.

**Comment by azaroth42** [comment]
![image](https://cloud.githubusercontent.com/assets/871868/14126500/3292de18-f5c6-11e5-8c27-4afd79b47303.png)

(copied from slack)
