### ISSUE TITLE
Should Places have geometries in MVP?

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#33]
@hybox/drs-team Is there a requirement for the geometry (polygon that delineates the space in lat/long terms for the Place) rather than just lat/long?  The value is clear (draw the polygon on a map) but the complexity is also high.  Seems like we can punt it to outside of the repo.

If so, how do we model it?

**Comment by no-reply** [comment]
Based on discussion w/ @hybox/drs-team, geometries can be punted.
