### ISSUE TITLE
Can Object hasMember Object in HyBoxPCDMWorks

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#34]
At LDCX, I believe that we created a subClass of pcdm:Object which was tentatively named ???:Part.  Objects hasMember Parts, and Parts (I think) hasMember Parts.

Can Object hasMember Object still, or is everything a Part?  Is the use case for Object hasMember Object the discovery one, where a Part should NOT be discovered separately from its Object, whereas an Object that's included can be separately discovered?

With much elision:

``` JSON
{
  "type": "Object",
  "label": "Atlas",
  "hasMember": [
    {
      "type": "Part",
      "label": "Boring Cover of Atlas"
    },
    {
      "type": "Object",
      "label": "Super Interesting Map that Happens To Be in Atlas"
    }
  ]
}
```

(Summoning @jpstroop @escowles @tpendragon @no-reply @mjgiarlo)

**Comment by escowles** [comment]
I think we called it a Part, but acknowledged that it was contextual.  So it was just an Object that was the member of some other Object, and in that context was considered a Part.

**Comment by azaroth42** [comment]
So no new subClass? That's fine by me :) We should discuss discoverability (in a separate issue, perhaps not even modeling related).

Others okay to close?

**Comment by tpendragon** [comment]
:+1: to closing.

**Comment by anarchivist** [comment]
:rocket:

**Comment by mjgiarlo** [comment]
:ok:

**Comment by azaroth42** [comment]
Closing -- no new subclass :)
