### ISSUE TITLE
Relationship between pcdm:X and rwo?

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#39]
We need a relationship for has-digital-representation / is-digital-representation-of to link between PCDM:\* and the real world object.

I think edm:isRepresentationOf is good for one direction, but we need from RWO to DO.

**Comment by azaroth42** [comment]
Tagging a bunch of people that might be interested: @anarchivist @no-reply @aisaac @escowles @jpstroop @cmh2166 @tpendragon @mjgiarlo

**Comment by cmharlow** [comment]
For what its worth, my notes from the (or one of the) Slack discussions with Rob around a particular instance of this question are below.

edm:isRepresentationOf has a domain of edm:InformationResource, a class which is equivalent to FRBR Work∪Expression∪Manifestation. I don't think this would be a problem for PCDM:*... but need to think it through more. It is a subclass of CIDOC-CRM:P138_represents, which does have an inverse property, but has domains/ranges tied to visual resources. So don't think we can just use the CRM properties.

I remain interested in the possibility of using edm:aggregatedCHO, making the RWO (in this example, a bibframe2:Item instance) also a edm:providedCHO. Leaves it open to possibly linking a PCDM:\* to a bibframe2:Instance (so not just RWOs) if wanted? Though isRepresentationOf does as well. And, well, still the question of an inverse.

bibframe2:hasItem has too\* restrictive domain/ranges. bibframe2:hasReproduction, same problem (expects domain/range of bibframe2:Instance).

Finally, we're somewhat capturing this relationship now by using boring dct:source (i.e. PCDM-Works:Work dct:source [Horrid BibIds of physical instances]), until we can find something better.

Sorry for the white board photo. 

![img_4184](https://cloud.githubusercontent.com/assets/6874040/14545044/13377348-026a-11e6-906a-a806cf7fb69e.JPG)

**Comment by aisaac** [comment]
fyi edm:isRepresentationOf has no domain, at least not in the EDM definition I see now. 
[true, it's said to be a sub-propertyof P138_represents, but we may not adhere very strongly to any domain/range there]

For info there was this document, which investigated a bit using isRepresentationOf between DOs and CHOs, in a library FRBR-ish context
http://pro.europeana.eu/files/Europeana_Professional/Projects/Project_list/EuropeanaLibraries/Deliverables/D5.1%20%20Alignment%20of%20library%20metadata.pdf
I'm sorry I won't have more time for this this week, really. You may want to ping @vcharles89 and @nfreire who were more involved than me in this report, actually.

**Comment by aisaac** [comment]
I think I've received a ping from @azaroth42 asking whether EDM could create an inverse property for edm:isRepresentationOf. Or I may have dreamed it (I can't find it anymore). Anyway, at the moment I would feel moderately enthusiastic about it. Creating inverses actually create some trouble for our providers and more work for us. We've got to create and maintain it, and then providers ask which one they should use.

**Comment by azaroth42** [comment]
That's fair. We can run with edm:isRepresentationOf and if we find a real need for the inverse, it's easy enough to mint in our own namespace. Thanks @aisaac!

**Comment by aisaac** [comment]
OK, great!

**Comment by azaroth42** [comment]
Closing issue: resolution is to use edm:isRepresentationOf and to mint an inverse if and when we need it.
