### ISSUE TITLE
dcterms:extent

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#47]
In DPLA MAP, dcterms:extent is used ... and the suggested object of the predicate is a Literal.  The actual range of the predicate is http://purl.org/dc/terms/SizeOrDuration.
EDM is silent about the domain/range. [p51 of v5.2.6]

Don't care?

**Comment by anarchivist** [comment]
Don't care. Europeana mostly has literals.

**Comment by azaroth42** [comment]
I'm good with that :)
