### ISSUE TITLE
Model: Accounts and Users

### ISSUE THREAD

**Issue by azaroth42** [hybox/models#6]
Should model the following:
- Accounts
- Agents: People / Organizations / Software
- Roles
- Events
- Acting onBehalfOf another Person or Organization

Use cases:
- Self-Submission
- Annotations (Comments, Tags, Reviews, etc)
- Access Rights
- Recommender systems
- Usage tracking / history
- Personalization

**Comment by azaroth42** [comment]
Ping @hybox/drs-team:

Unless you have further guidance, we'll run with Accounts being a required model and linked to Persons (or other Agents like Organization or SoftwareApplication). Please let us know any requirements, otherwise we'll take a best guess :)

**Comment by hannahfrost** [comment]
:+1:

**Comment by no-reply** [comment]
[This image](https://files.slack.com/files-pri/T0600BRLJ-F0V2W5APL/imag0471.jpg) is a sketch of the Agent, Account, and ACL models. Note that the ACL/Auth relationships (the bottom right) is slightly flattened in the drawing. The full structure is as documented at [WebACL](https://www.w3.org/wiki/WebAccessControl).

In summary:
- `foaf:Account`s are used for sign-on/identification; they are `sioc:account_of` ~~(? see #30)~~ a `foaf:Agent`.
  - We model accounts for completeness, but make no assumption that they will be implemented as repository objects. They may be managed by a database, etc...
- Agents may be People, Groups, Organizations. They represent real entities.
  - We identified and verified the use case that an authorization Agent and a metadata Agent (e.g. a `dc:creator`) may be the same person, so we make no distinction between these Agent types.
- Agents may be `org:memberOf` ~~(? see #30)~~ any `foaf:Group`.
- Groups may be for authorization purposes only, or used for metadata.
  - Do we have use cases for authenticating on groups that are used in a metadata context (e.g. an academic department?; cc: @hybox/drs-team ).
- An Authorization has either an `acl:agent` which is an Agent, or an `acl:agentClass` which is a Group.

@azaroth42, @awoods we talked a bit about the IP authentication use case: do we want to consider the possibility of using `acl:trustedOrigin` for these kinds of cases?

**Comment by azaroth42** [comment]
:+1: to the write-up above

**Comment by azaroth42** [comment]
Diagram of above whiteboard:
![hybox-acls](https://cloud.githubusercontent.com/assets/871868/14003398/8f530d6e-f10f-11e5-893e-3d86bd9898ca.png)

**Comment by azaroth42** [comment]
This issue can be closed when the above documentation is available in models/permissions.md.

**Comment by anarchivist** [comment]
> @azaroth42, @awoods we talked a bit about the IP authentication use case: do we want to consider the possibility of using `acl:trustedOrigin` for these kinds of cases?

`acl:trustedOrigin` doesn't exist in the BasicAccessControl vocabulary yet. I'm creating a new issue to track IP-based auth.

**Comment by anarchivist** [comment]
Closed by #54
